import random
def roast():
    roast = [
    "Where is your off button?",
    "I know you don't like me, and that implies you need better taste.",
    "I'm no astronomer, but I'm pretty sure the Earth revolves around the sun… not you.",
    "I'd give you a nasty look, but it seems like you've already got one.",
    "Your birth certificate should be rewritten as a letter of apology.",
    "You haven't changed since the last time I saw you. You really should.",
    "Your bad personality is the reason I prefer animals to humans.",
    "You hear that? It's the sound of me not caring.",
    "I might be fully vaccinated, but I'm still not going to hang out with you.",
    "You're so annoying, you could make a Happy Meal cry.",
    "Oh, sorry, did the middle of my sentence interrupt the beginning of yours?",
    "You know, you're just not pretty enough to have such an ugly personality.",
    "You just might be why the middle finger was invented in the first place.",
    "You have a face that makes onions cry.",
    "Have a nice day… somewhere else.",
    "You do realize we're just tolerating you, right?",
    "Were you born this stupid or did you take lessons?",
    "It's really fun watching you try to understand everything that's being said about you.",
    "You are even more useless than the 'ueue' in queue.",
    "The real heroes in this world are the ones who have to live with you.",
    "Somewhere out there a tree is producing oxygen for you. What a shame.",
    "Everyone is allowed to act stupid once in a while, but you're really abusing the privilege.",
    "If you're going to be two-faced, at least make one of them pretty.",
    "I was today years old when I realized I didn't like you.",
    "I'm not a nerd; I'm just smarter than you.",
    "If I had a dollar every time you shut up, I would give it back as a thank you.",
    "I didn't mean to offend you… but I'll take it as an additional perk.",
    "I don't want to rain on your parade. I want to summon a typhoon.",
    "You can't imagine how much happiness you can bring… by leaving the room.",
    "I've been called worse things by better men.",
    "I didn't mean to push your buttons, I was just looking for mute.",
    "I forgot the world revolves around you. My apologies! How silly of me.",
    "I'd rather treat a baby's diaper rash than have lunch with you.",
    "I would smack you, but I'm against animal abuse.",
    "I gave out all my trophies a while ago, but here's a participation award.",
    "It's all about balance… you start talking, I stop listening.",
    "You're the reason this country has to put directions on shampoo bottles.",
    "How many licks 'till I get to the interesting part of this conversation?",
    "When you start talking, I stop listening.",
    "I'm listening. I just need a minute to process so much stupid information at once.",
    "You are like a software update. Every time I see you, I immediately think 'not now.'",
    "Don't worry… the first 40 years of childhood are always the hardest.",
    "It's impossible to underestimate you.",
    "I like the way you comb your hair. It's impressive how you're able to hide the horns.",
    "If I throw a stick, will you chase it? I really want out of this conversation.",
    "You're the reason gene pools need lifeguards.",
    "I don't know what makes you so stupid, but it's really doing the job.",
    "The truth will set you free. You're the worst. OK, you're free to go.",
    "Do you think your parents realize that they're living proof that two wrongs don't make a right?",
    "Give me a minute; I'm trying to think of an insult simple enough for you to understand!",
    "I know our son got his brains from you because, well, I still have mine.",
    "I've heard a smarter statement come out in a fart.",
    "I look at you and think… two billion years of evolution for this?",
    "I told my therapist about you. She didn't believe me.",
    "Don't be ashamed of who you are. That's a job for your parents.",
    "When I listen to you, I think you really are going to go far. I hope you stay there.",
    "When I see you coming, I get pre-annoyed. I figure it's smart to give myself a head start.",
    "Whoever told you to be yourself gave you bad advice.",
    "I think you just need a high five… in the face… with a chair.",
    "We were happily married for one month. Unfortunately, we've been married for 10 years.",
    "When I look at you, I think to myself where have you been my whole life? And can you go back there?",
    "Light travels faster than sound. It explains why you seemed smart… until I finally heard you speak.",
    "Your secrets are always safe with me. I don't even listen when you share them.",
    "When God made you, you must have been on the bottom of his 'to-do' list.",
    "Everyone brings happiness to a room. I bring happiness when I walk in, and you bring happiness when you leave.",
    "Sweetheart, the only thing bothering me is that thing between your ears.",
    "Your face is fine, but you really should put a bag over that personality.",
    "I would call you an idiot, but it would be an insult to stupid people.",
    "Are you at a loss for words, or did you exhaust your entire vocabulary?",
    "Accidents happen; the proof is sitting right there.",
    "You bring everyone so much joy… when you leave the room.",
    "You're not simply a drama queen. You're the whole royal family.",
    "You're like a gray sprinkle on a rainbow cupcake.",
    "No, that's fine. You're certainly entitled to your incorrect opinion.",
    "You are more disappointing than an unsalted pretzel.",
    "I can't wait to spend my whole life without you.",
    "Rolling your eyes isn't going to help you find your brain.",
    "A glowstick has a brighter future than you. Lasts longer, too.",
    "If you ever need to find higher ground, you can always try climbing up your own ego.",
    "You are the human version of cramps.",
    "I don't know what makes you so stupid, but it's really doing the job.",
    "The truth will set you free. You're the worst. OK, you're free to go.",
    "Do you think your parents realize that they're living proof that two wrongs don't make a right?",
    "Give me a minute; I'm trying to think of an insult simple enough for you to understand!",
    "I know our son got his brains from you because""I know our son got his brains from you because, well, I still have mine.",
"I've heard a smarter statement come out in a fart.",
"I look at you and think… two billion years of evolution for this?",
"I told my therapist about you. She didn't believe me.",
"Don't be ashamed of who you are. That's a job for your parents.",
"When I listen to you, I think you really are going to go far. I hope you stay there.",
"When I see you coming, I get pre-annoyed. I figure it's smart to give myself a head start.",
"Whoever told you to be yourself gave you bad advice.",
"I think you just need a high five… in the face… with a chair.",
"We were happily married for one month. Unfortunately, we've been married for 10 years.",
"When I look at you, I think to myself where have you been my whole life? And can you go back there?",
"Light travels faster than sound. It explains why you seemed smart… until I finally heard you speak.",
"Your secrets are always safe with me. I don't even listen when you share them.",
"When God made you, you must have been on the bottom of his 'to-do' list.",
"Everyone brings happiness to a room. I bring happiness when I walk in, and you bring happiness when you leave.",
"Sweetheart, the only thing bothering me is that thing between your ears.",
"Your face is fine, but you really should put a bag over that personality.",
"I would call you an idiot, but it would be an insult to stupid people.",
"Are you at a loss for words, or did you exhaust your entire vocabulary?",
"Accidents happen; the proof is sitting right there.",
"You bring everyone so much joy… when you leave the room.",
"You're not simply a drama queen. You're the whole royal family.",
"You're like a gray sprinkle on a rainbow cupcake.",
"No, that's fine. You're certainly entitled to your incorrect opinion.",
"You are more disappointing than an unsalted pretzel.",
"I can't wait to spend my whole life without you.",
"Rolling your eyes isn't going to help you find your brain.",
"A glowstick has a brighter future than you. Lasts longer, too.",
"If you ever need to find higher ground, you can always try climbing up your own ego.",
"You are the human version of cramps.",
"I don't know what makes you so stupid, but it's really doing the job.",
"The truth will set you free. You're the worst. OK, you're free to go.",
"Do you think your parents realize that they're living proof that two wrongs don't make a right?",
"Give me a minute; I'm trying to think of an insult simple enough for you to understand!",
"I know our son got his brains from you because" "I’m not saying you’re ugly, but if I throw a stick, you fetch the b*stard and bring it back.",
    "You act like how I would think vomit would act if it could.",
    "I thought of you today, and it reminded me to take out the trash.",
    "I’d give you a nasty look, but you already got one.",
    "I'm not an astronomer, but I am pretty sure the world revolves around the sun, not you.",
    "You and I go way back, and you’ve always been annoying. I mean, you even used to make your happy meal cry.",
    "It’s not that you’re annoying; it’s just that I’d liken you to the human version of period cramps.",
    "Are you done with all of this drama? Because I need an intermission.",
    "I apologize for doing anything that made you believe I care about how you feel.",
    "Most mistakes can be fixed; you are the exception that proves the rule.",
    "Everyone can act foolish once, but you are violating that privilege.",
    "If you’re offended by my opinion, you should hear the ones I keep to myself.",
    "You remind me of a cloud; my day becomes much brighter when you disappear.",
    "You are like a software update. Whenever I see you, I immediately think, 'not now.'",
    "If your mum got given one piece of bad advice, it was not to swallow.",
    "You're like the human version of an athlete's foot; annoying and hard to get rid of.",
    "Looking at you reminded me to take my contraception. I can’t risk giving birth to someone that ugly.",
    "It is hilarious how you are trying to fit your entire vocabulary into one sentence.",
    "If ignorance is bliss, you must be the happiest person on the planet.",
    "I’m trying to come up with an insult that’s stupid enough for you to realize, so give me a moment.",
    "You're talking to me; I thought you only talked behind my back.",
    "I've seen you before, but I'm sure I had to pay for admission last time.", "I love what you’ve done with your hair. How do you get it to come out of your nostrils like that?",
    "Your secrets are always safe with me, and I never even listen when you tell me them.",
    "So a thought crossed your mind? That must have been a long and lonely journey for you.",
    "If you’re going to be two-faced, at least make one of them pretty.",
    "You must have been born on a highway because that's where most accidents happen.",
    "When I look at you, I wonder where you have been all my life… Would you mind returning there?",
    "I’m sorry that my brutal honesty inconvenienced your ego.",
    "Laughter is the only best medicine your face must cure the world.",
    "Do you think this hurts my feelings? The only thing that hurts is my eyes when I'm looking at you.",
    "Watching you attempt to use all of your vocabularies in a single statement is funny.",
    "Don't feel bad. A lot of people have no talent.",
    "Why don't you go play in traffic?",
    "I never forget a person’s face, but I’ll be happy to make an exception in your situation.",
    "You should carry a plant around to replace the oxygen you waste.",
    "Some people are like slinkies. They are not good for much, but they bring a smile to your face when pushed down the stairs.",
    "You must have been born on a highway because that is where more accidents happen.",
    "The only reason I go with you everywhere is that I’d rather do that than kiss your ugly face goodbye.",
    "I thought I had the flu, but then I realized your face makes me sick to my stomach.",
    "I could eat a bowl of alphabet soup and poop out a smarter statement than you said.",
    "I forgot that the rest of the world revolves around you. How foolish of me; my apologies.",
    "When I saw your face, the only thing I would have changed was the direction I was heading in.",
    "I would punch you, but I don’t want to improve the appearance of your face.",
    "Accidents happen; the proof is sitting right there.", "Oh, I’m sorry. Did the middle of my sentence interrupt the beginning of yours?",
    "Light travels faster than sound, which is why you seemed bright until you spoke.",
    "The only way you'd get hurt from exercising would be if you sprained your finger changing the channel.",
    "You are proof God has a sense of humour. I heard you got a job as a weatherman. Good luck trying to predict your next move.",
    "I think I found your purpose in life. It is to be an organ donor.",
    "You have an entire life to be an idiot. Why not take today off?",
    "I’m sorry I upset you by calling you a h*e. I was unaware that it was a secret.",
    "Amazingly, you don't allow your knowledge to stand in the way of stupidity. Don’t attempt to think too much. Your stupidity might injure your brain.",
    "Your parents really must have been happily married before they had you.",
    "Mirrors can’t talk. Lucky for you, they can’t laugh, either.",
    "I know people put you down, but I think you will go far personally, and I hope you stay there.",
    "I am not ignoring you. I am simply giving you time to reflect on what an idiot you are.",
    "I keep thinking you can't get any dumber, and you keep proving me wrong.",
    "I'd be broke if I had a dollar for every time you said something smart.",
    "Somewhere out there is a tree tirelessly producing oxygen for you. You owe it an apology.",
    "I apologize if my forced apology sounded fake; I’ll work to improve it the next time.",
    "Don’t hate me because I’m beautiful. Hate me because your boyfriend thinks so.",
    "I'm not insulting you; I'm describing you. Your bad personality is the reason I prefer animals to humans.",
    "You are so unattractive that your reflection tries to walk away when you glance in the mirror.",
    "I'm not saying you're ugly, but nobody wants to sleep with you because they don't want to be prosecuted for animal abuse.",
     "Even though it might appear like I'm paying attention to you, I simply imagine duct tape across your lips.",
    "It’s not that I don’t listen to you when you talk. It’s just that there is only so much stupid information I can process in one go.",
    "You’re like the first slice of bread in a loaf. You get touched by everybody but wanted by none.",
    "I believe you can achieve anything. Look around you; there are remarkably dumb people everywhere who you could aspire to be.",
    "It seems your face caught fire, and somebody attempted to stop it with a hammer.",
    "Feed your own ego. I’m busy.",
    "I’m not stating you’re stupid, but a glowstick has a better future than you have.",
    "It must be fun to wake up each morning knowing that you are that much closer to achieving your dreams of complete and utter mediocrity.",
    "You just might be why the middle finger was invented in the first place.",
    "You are evidence that evolution can go backwards.",
    "There’s somebody out there for everybody. For you, it’s a psychiatrist.",
    "If I had a face like yours, I would sue my parents.",
    "This will be the first and last roast of the night, as we’ve already used up your entire vocabulary.",
    "You have no idea how much joy you may spread just by leaving the room.",
    "I don't know if I should insult or congratulate you for saying something without drooling.",
    "It's kind of sad what happened to your face... Oh wait, that's how it has always looked?",
    "Sometimes it's better to keep your lips shut and make people think you're ignorant than to open them and clear all doubt.",
    "I’ve heard a smarter statement come out in a fart.",
    "Hold still. I’m trying to imagine you with a personality.",
    "I don't hate you, but I would give you a high five if you drowned.",
    "When you were born, the doctors probably threw you out of the window, and the window threw you back.",
    "Someday, you'll go far. And I hope you stay there.",
    "It’s impossible to underestimate you. We were going to roast you, but it's not good for the environment to burn trash."
]
    return (random.choice(roast))

def b_msg():
    msg = [
    "🎉🎂\nMay your day be filled with joy and laughter! 🥳",
    "🎈🎁\nWishing you a fantastic birthday! May your year ahead be amazing! 🌟",
    "🎂🎉\nHere's to another year of incredible adventures! 🚀",
    "🎊🎂\nWishing you a day full of love, happiness, and lots of surprises! 🎁",
    "🥂🎉\nCheers to another year of life's wonderful journey! Happy Birthday! 🎂",
    "🌈🎈\nMay this birthday bring you all the happiness and success you deserve! 🌟",
    "🎂🎁\nMay the coming year be filled with prosperity and joy! Happy Birthday! 🥳",
    "🎉🎂\nWishing you a day as special as you are! Happy Birthday! 🌟",
    "🎁🌟\nMay your birthday be the start of a year filled with good luck and happiness! 🎂",
    "🎉🎂\nHere's to making more wonderful memories in the coming year! 🌈",
    "🎊🎂\nWishing you health, happiness, and all the success in the world! 🌟",
    "🎈🎁\nMay your day be as bright and beautiful as your smile! 😊",
    "🎉🎂\nMay this special day bring you all the joy and blessings you've been wishing for! 🌟",
    "🎂🎉\nMay your dreams and aspirations come true in the year ahead! 🌟",
    "❤️🎈\nWishing you a birthday filled with love, laughter, and all your heart desires!",]
    return random.choice(msg)

def b_gif():
    gif = [
    "https://media1.tenor.com/m/rLvxaSCdYOcAAAAC/happy-16th-birthday.gif",
    "https://media1.tenor.com/m/ll2aH9XhvfMAAAAd/babytaty.gif",
    "https://media1.tenor.com/m/bNKDzPJL8aYAAAAC/beagle-beagle-sunnies.gif",
    "https://media1.tenor.com/m/sdmIWCbSIFoAAAAC/birthday-wishes-birthday-for-dog-lovers.gif",
    "https://media1.tenor.com/m/xkLr-x9gzjQAAAAC/happ-birthday-kiss.gif",
    "https://media1.tenor.com/m/Uk21ev0V32cAAAAd/happy-birthday.gif",
    "https://media1.tenor.com/m/sjbgFaJ6MNcAAAAC/do-you-remember.gif",
    "https://media1.tenor.com/m/y5IIJSSpfTAAAAAC/birthday-birthday-wishes.gif",
    'https://media1.tenor.com/m/pJELTZNWqT4AAAAC/happybirthday-dog.gif',
    'https://media.giphy.com/media/RyqiL8NJMUzvi/giphy.gif',
     'https://media.giphy.com/media/Bqz89EFuBgH4GTBpON/giphy-downsized-large.gif',
     'https://media.giphy.com/media/3o6gbbbGbpBZCRm15C/giphy.gif']
    return random.choice(gif)
